# Generated by Django 4.2.1 on 2023-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelTitle', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('viewCount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
