# Generated by Django 4.2.1 on 2023-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.TextField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('author_info', models.CharField(max_length=255)),
                ('author_profile_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='YouTobeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('channelTitle', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('viewCount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
