# Generated by Django 4.2.1 on 2023-06-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtobemodel_delete_contentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtobemodel',
            name='video_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
